"""A shareable, deterministic handoff document for a session.

``handoff`` bundles the evidence-cited recap into a single Markdown artifact a
human can save, paste into a ticket, or hand to a teammate: who/what/where, an
optional "what changed since you last looked" section, the full brief, and a
read-only provenance footer. No LLM — every line still cites its transcript
evidence, and it works for any agent the normalized model covers.
"""

from __future__ import annotations

import os
from typing import Optional

from . import assess as A
from . import brief as B
from . import state as S
from .brief import _oneline
from .since import SinceView


def default_filename(tr, agent: str = "claude", stamp: str = "") -> str:
    sid = (tr.session_id[:8] if getattr(tr, "session_id", "") else "session")
    proj = os.path.basename((getattr(tr, "cwd", "") or "").rstrip(os.sep)) or "project"
    date = (stamp or "").replace(":", "").replace(" ", "-")[:15] or "now"
    return f"handoff-{proj}-{agent}-{sid}-{date}.md"


def render(st: S.State, *, agent: str = "claude", generated_at: str = "",
           since_view: Optional[SinceView] = None) -> str:
    tr = st.tr
    a = A.assess(st)
    L = []
    push = L.append

    title = tr.title or (st.intents[-1].text if st.intents else "(untitled)")
    push(f"# Handoff — {_oneline(title, 70)}")
    push("")
    meta = [
        f"- **Agent:** {agent}",
        f"- **Session:** `{tr.session_id[:8] if tr.session_id else '?'}`",
        f"- **Project:** `{tr.cwd or '?'}`"
        + (f" · branch `{tr.git_branch}`" if tr.git_branch else ""),
        f"- **Status:** {st.status} · **Safety:** {a.verdict}",
    ]
    if generated_at:
        meta.append(f"- **Generated:** {generated_at} (read-only; from the session transcript)")
    L.extend(meta)
    push("")

    if since_view is not None and since_view.has_changes:
        push("## While you were away")
        push("")
        # the since body already has its own H1; demote to fit under this section
        push(_demote_headings(since_view.text))
        push("")

    push("## Full brief")
    push("")
    push(B.render(st))
    push("")
    push("---")
    push("_Generated by cc-copilot — a read-only observer. Every `[L…]` is a line "
         "in the agent's session transcript; nothing here is stated without that "
         "evidence._")
    return "\n".join(L)


def _demote_headings(md: str) -> str:
    """Push every Markdown heading one level deeper so an embedded doc nests."""
    out = []
    for line in md.splitlines():
        if line.startswith("#"):
            out.append("#" + line)
        else:
            out.append(line)
    return "\n".join(out)
